import json
import os

nb_path = '/projects/sccn/andromeda1/aglinska/deepcor-fmri-toolbox/tests/01-StudyForrest-advanced-train-v1.ipynb'

with open(nb_path, 'r') as f:
    nb = json.load(f)

# Content patches from previous step
cell_38_source = [
    "# Define prepare_confounds function\n",
    "def prepare_confounds(df, conf_cols):\n",
    "    \"\"\"\n",
    "    Prepare confound regressor matrix from dataframe.\n",
    "    \n",
    "    Args:\n",
    "        df: Confounds dataframe\n",
    "        conf_cols: List of column names to use\n",
    "        \n",
    "    Returns:\n",
    "        Tensor of shape [n_confounds, n_timepoints]\n",
    "    \"\"\"\n",
    "    # Select columns\n",
    "    df_metrics = df[conf_cols].copy()\n",
    "    \n",
    "    # Fill NaNs\n",
    "    df_metrics = df_metrics.fillna(0)\n",
    "    \n",
    "    # Z-score normalization\n",
    "    df_metrics = (df_metrics - df_metrics.mean()) / (df_metrics.std() + 1e-8)\n",
    "    \n",
    "    # Convert to tensor and transpose to [channels, time]\n",
    "    conf_tensor = torch.tensor(df_metrics.values, dtype=torch.float32).T\n",
    "    \n",
    "    return conf_tensor\n",
    "\n",
    "# Step 1: Data preprocessing\n",
    "print(\"Preprocessing data...\")\n",
    "n_dummy_scans = config.data.n_dummy_scans\n",
    "confound_columns = config.data.confound_columns\n",
    "\n",
    "# Apply dummy scan removal\n",
    "epi, df_conf = apply_dummy(epi, df_conf, n_dummy_scans)\n",
    "\n",
    "# Prepare confounds\n",
    "conf_tensor = prepare_confounds(df_conf, confound_columns)\n",
    "\n",
    "# ADD BATCH DIMENSION [1, Channels, Time]\n",
    "conf_tensor = conf_tensor.unsqueeze(0)\n",
    "print(f\"Confounds shape: {conf_tensor.shape}\")\n",
    "\n",
    "# Prepare voxel lists\n",
    "print(\"Extracting voxel lists...\")\n",
    "# Note: get_obs_noi_list_coords returns (obs_list_coords, noi_list_coords, gm, cf)\n",
    "obs_list_coords, noi_list_coords, gm, cf = get_obs_noi_list_coords(epi, gm, cf)\n",
    "\n",
    "# Move confounds to device\n",
    "conf_tensor = conf_tensor.to(device)"
]

cell_46_source = [
    "# Helper variables\n",
    "nTR = epi.shape[-1]\n",
    "t_r = 2.0 # Standard TR, adjust if known from header\n",
    "print(f\"nTR: {nTR}\")\n",
    "\n",
    "# Create DataLoaders\n",
    "# We need to construct a dataset from the coordinates/values\n",
    "train_dataset = TrainDataset(obs_list_coords, noi_list_coords)\n",
    "train_loader = torch.utils.data.DataLoader(\n",
    "    train_dataset, \n",
    "    batch_size=config.training.batch_size, \n",
    "    shuffle=True, \n",
    "    drop_last=True\n",
    ")\n",
    "print(f\"DataLoader created with batch size {config.training.batch_size}\")\n",
    "\n",
    "# Initialize Model\n",
    "# We pass the Prepared confounds tensor here\n",
    "model = MODEL(\n",
    "    conf=conf_tensor,\n",
    "    in_channels=4, # (val, x, y, z)\n",
    "    in_dim=nTR,\n",
    "    latent_dim=config.model.latent_dims,\n",
    "    beta=config.model.beta,\n",
    "    gamma=config.model.gamma,\n",
    "    delta=config.model.delta,\n",
    "    scale_MSE_GM=config.model.scale_MSE_GM,\n",
    "    scale_MSE_CF=config.model.scale_MSE_CF,\n",
    "    scale_MSE_FG=config.model.scale_MSE_FG,\n",
    "    do_disentangle=config.model.do_disentangle\n",
    ")\n",
    "\n",
    "model = model.to(device)\n",
    "print(\"Model initialized and moved to device\")\n",
    "\n",
    "# Initialize Trainer\n",
    "trainer = Trainer(\n",
    "    model,\n",
    "    device=device,\n",
    "    optimizer_type=config.training.optimizer,\n",
    "    lr=config.training.learning_rate,\n",
    "    betas=config.training.betas,\n",
    "    eps=config.training.eps,\n",
    "    max_grad_norm=config.training.max_grad_norm\n",
    ")\n",
    "print(\"Trainer initialized\")\n",
    "\n",
    "# Train the model\n",
    "print(f\"Starting training for {config.training.n_epochs} epochs...\")\n",
    "# We use a simple tracking dict for visualization\n",
    "keys = [\n",
    "    'l', 'kld_loss', 'recons_loss_roi', 'recons_loss_roni',\n",
    "    'loss_recon_conf_s', 'loss_recon_conf_z', 'ncc_loss_tg',\n",
    "    'ncc_loss_bg', 'ncc_loss_conf_s', 'ncc_loss_conf_z',\n",
    "    'smoothness_loss', 'recons_loss_fg'\n",
    "]\n",
    "track = init_track(keys)\n",
    "\n",
    "# Training loop\n",
    "loss_history = []\n",
    "for epoch in range(config.training.n_epochs):\n",
    "    # Train one epoch\n",
    "    avg_loss = trainer.train_epoch(train_loader)\n",
    "    loss_history.append(avg_loss)\n",
    "    \n",
    "    # Update tracking (using a batch from loader for viz)\n",
    "    with torch.no_grad():\n",
    "        # Get a sample batch\n",
    "        sample_batch = next(iter(train_loader))\n",
    "        inputs_gm = sample_batch[0].to(device)\n",
    "        inputs_cf = sample_batch[1].to(device)\n",
    "        \n",
    "        # Update track\n",
    "        track = update_track(track, model, inputs_gm, inputs_cf)\n",
    "    \n",
    "    if (epoch + 1) % 10 == 0 or epoch == 0:\n",
    "        print(f\"Epoch {epoch+1}/{config.training.n_epochs}, Loss: {avg_loss:.4f}\")\n",
    "\n",
    "# Save outputs\n",
    "print(\"Saving model and results...\")\n",
    "# Save checkpoint\n",
    "trainer.save_checkpoint(\n",
    "    os.path.join(output_dir, 'model_final.pt'), \n",
    "    config.training.n_epochs, \n",
    "    avg_loss\n",
    ")\n",
    "\n",
    "# Save track\n",
    "save_track(os.path.join(output_dir, 'track.pickle'), track)\n",
    "\n",
    "# Generate and save denoised brain files\n",
    "print(\"Generating denoised brain signals...\")\n",
    "save_brain_signals(\n",
    "    model, \n",
    "    train_dataset, \n",
    "    epi, \n",
    "    gm, \n",
    "    os.path.join(output_dir, 'denoised_deepcor.nii.gz'), \n",
    "    kind='FG'\n",
    ")\n",
    "\n",
    "# Also calculate compcor for comparison\n",
    "print(\"Calculating CompCor...\")\n",
    "calc_and_save_compcor(\n",
    "    epi, \n",
    "    gm, \n",
    "    cf, \n",
    "    os.path.join(output_dir, 'denoised_compcor.nii.gz'), \n",
    "    n_components=5\n",
    ")\n",
    "\n",
    "print(\"Done!\")\n"
]

cell_34_source = [
    "epi = ants.image_read(epi_path)\n",
    "df_conf = pd.read_csv(confounds_path, sep='\\t') # Use tab separator\n",
    "gm = ants.image_read(gm_mask_path)\n",
    "cf = ants.image_read(cf_mask_path)"
]

# Update content
for cell in nb['cells']:
    source_txt = "".join(cell['source'])
    
    if "def prepare_confounds" in source_txt:
        cell['source'] = cell_38_source
        cell['execution_count'] = None
        cell['outputs'] = []

    # Other cells shouldn't be overwritten blindly if they correct, but we defined them constant in script
    # Let's hope logic holds. Yes.

with open(nb_path, 'w') as f:
    json.dump(nb, f, indent=1)
print("Notebook confounds dimensionality fix applied.")
